"""Plot results generated by simulation_student.py."""
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

RESULT_DIR = Path("results")
FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)

ELEVATION_ANGLES_DEG = np.arange(5, 91, 5)
# Maps are more numerous, so keep a useful subset by default.
MAP_ANGLES_DEG = [5, 15, 25, 35, 45, 55, 65, 75, 85, 90]


def plot_ecdf(values, label):
    values = np.sort(np.asarray(values))
    y = np.arange(1, len(values) + 1) / len(values)
    plt.plot(values, y, label=label)


def plot_all_ecdfs():
    for angle in ELEVATION_ANGLES_DEG:
        rician_file = RESULT_DIR / f"macro_with_Rician{int(angle)}deg_100km.json"
        macro_file = RESULT_DIR / f"macro_no_Rician{int(angle)}deg_100km.json"
        with open(rician_file) as f:
            rician = json.load(f)
        with open(macro_file) as f:
            macro = json.load(f)

        plt.figure(figsize=(8, 5))
        plot_ecdf(rician["sinr"], "Rician SINR")
        plot_ecdf(rician["snr"], "Rician SNR")
        plot_ecdf(macro["sinr"], "Macro SINR")
        plot_ecdf(macro["snr"], "Macro SNR")
        plt.xlabel("S(I)NR (dB)")
        plt.ylabel("ECDF")
        plt.title(f"LEO multi-beam performance — {angle}° elevation")
        plt.grid(True)
        plt.legend()
        plt.tight_layout()
        plt.savefig(FIG_DIR / f"ECDF_{int(angle)}deg.png", dpi=150)
        plt.close()


def plot_selected_maps():
    for angle in MAP_ANGLES_DEG:
        filename = RESULT_DIR / f"macro_no_Rician{int(angle)}deg_100km.json"
        with open(filename) as f:
            result = json.load(f)

        user_pos = np.asarray(result["user_positions"])
        beam_index = np.asarray(result["beam_index"])
        beam_centers = np.asarray(result["beam_centers"])
        snr = np.asarray(result["snr"])
        sinr = np.asarray(result["sinr"])
        gain = np.asarray(result["center_beam_gain_dB"])

        maps = [
            (snr, "SNR (dB)", f"SNR_map_{int(angle)}deg.png"),
            (sinr, "SINR (dB)", f"SINR_map_{int(angle)}deg.png"),
            (gain, "Center beam gain (dB)", f"BeamGain_map_{int(angle)}deg.png"),
        ]
        for values, label, filename_out in maps:
            plt.figure(figsize=(7, 6))
            plt.scatter(user_pos[0] / 1000, user_pos[1] / 1000, c=values, s=35)
            plt.colorbar(label=label)
            plt.xlabel("x (km)")
            plt.ylabel("y (km)")
            plt.title(f"{label} — {angle}° elevation")
            plt.axis("equal")
            plt.tight_layout()
            plt.savefig(FIG_DIR / filename_out, dpi=150)
            plt.close()

        plt.figure(figsize=(7, 6))
        plt.scatter(user_pos[0] / 1000, user_pos[1] / 1000, c=beam_index, s=35)
        plt.scatter(beam_centers[0] / 1000, beam_centers[1] / 1000,
                    marker="x", s=80, linewidths=2)
        plt.xlabel("x (km)")
        plt.ylabel("y (km)")
        plt.title(f"Beam association — {angle}° elevation")
        plt.axis("equal")
        plt.tight_layout()
        plt.savefig(FIG_DIR / f"BeamAssociation_{int(angle)}deg.png", dpi=150)
        plt.close()


def main():
    plot_all_ecdfs()
    plot_selected_maps()
    print("Plots generated in the figures/ folder.")


if __name__ == "__main__":
    main()
